#ifndef _ENA_CONFIG_H_
#define _ENA_CONFIG_H_
#define ENA_HAVE_CPUMASK_LOCAL_SPREAD 1
#define ENA_HAVE_ETH_HW_ADDR_SET 1
#define ENA_NAPI_ALLOC_SKB_EXPLICIT_GFP_MASK 1
#define ENA_ETHTOOL_NFC_IPV6_SUPPORTED 1
#endif /* _ENA_CONFIG_H_ */
